### ISSUE TITLE
Custom log file

### ISSUE THREAD

**Issue by michaelachrisco** [tightenco/quicksand#2]
Awesome job! You guys are on the ball with these packages! Before, I was doing this via cron and a small service. 

I was wondering if it was possible to add in a custom path for log files within the config file? I can add a quick PR after the test suite is up and running.

**Comment by besologic** [comment]
@michaelachrisco that's a great idea! I just pushed up a test suite, so feel free to do a PR for this :)

**Comment by LKDevelopment** [comment]
Implemented and merged with #17  :D
