### ISSUE TITLE
needs: withoutGlobalScopes() ?

### ISSUE THREAD

**Issue by tanthammar** [tightenco/quicksand#21]
Sorry for posting a question, not an error.
Don't know where to reach you...

I have global scopes applied to models that also uses Quicksand.
The scope requires auth()->user() and filters on auth()->user()->currentTeam.

Will this cause a conflict w Quicksand?
Do I need to apply withoutGlobalScopes() somewhere  - to Quicksand forceDelete() query?

-------------
My global scope trait

trait UsedByTeams
{
	protected static function boot()
    {
        parent::boot();
            
        static::addGlobalScope('team', function(Builder $builder)
        {
            static::teamGuard();

            $builder->where('team_id', auth()->user()->currentTeam->id);
        });

        static::saving(function (Model $model)
        {
            static::teamGuard();
            
            if( ! isset($model->team_id))
            {
                $model->team_id = auth()->user()->currentTeam->id;                
            }
        });
    }

    public function scopeAllTeams($query)
    {
    	return $query->withoutGlobalScope('team');
    }

    public function team()
    {
    	return $this->belongsTo('App\Team');
    }

    protected static function teamGuard()
    {
        if(auth()->guest() || ! auth()->user()->currentTeam)
        {
            throw new \Exception('No Auth User/Team');
        }
    }
}

**Comment by imjohnbon** [comment]
Hi @tanthammar! Great question. I'm going to dig into this a little bit and get back to you shortly.

**Comment by imjohnbon** [comment]
Hi @tanthammar, just wanted to follow up here again. After doing some testing within the package and on a test Laravel app, I was able to confirm that Quicksand already disregards global scopes when it deletes old models. This is because under the hood it uses Laravel's `forceDelete` method, which itself disregards any global scopes. So there should be no need for you to add `
