### ISSUE TITLE
Intermediate Tables without model

### ISSUE THREAD

**Issue by palomamtnez** [tightenco/quicksand#26]
Is it a way to use Quicksand for intermediate tables, as they don't have a model in my application?

It works perfectly fine for my model User and Project, but I have a intermediate table user_project without a model (but with soft deletes) so is there a way to also register it on config/quicksand.php ?

**Comment by mattstauffer** [comment]
@palomamtnez That's a great question! I don't believe there is at the moment but that would be a great addition to the project.

**Comment by Jhnbrn90** [comment]
I tried to address this issue in PR #27. 

I don't know if I have the most elegant solution, but maybe it's a start 😄

**Comment by josecanhelp** [comment]
@palomamtnez I'm interested in how you set your pivot table with soft delete and no model. What does your migration for that table look like? How do you soft delete a row?

**Comment by Jhnbrn90** [comment]
> @palomamtnez What does your migration for that table look like? 

You could add a 'deleted_at' column manually to the pivot table migration or use `$table->softDeletes()` in the Schema builder. 

For example:
```php
public function up()
    {
        Schema::create('project_user', function (Blueprint $table) {
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('project_id');

            $table->unique(['user_id', 'project_id']);

            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('project_id')->references('id')->on('projects')->onDelete('cascade');

            $table->softDeletes();
        });
    }
```

> @palomamtnez How do you soft delete a row?

I am not 100% sure, but if you'd ask me, this would be my approach:



Define the relationship in the Project model (I'll use the example of Users and Projects):

```php
public function users()
    {
    	return $this->belongsToMany(User::class)->wherePivot('deleted_at', null);
    }
```

Then, calling `$project->users()->where(...)` or `$project->users` will only yield the non soft deleted results. If you want to include them, you could add a method yourself:

```php
public function usersWithTrashed()
    {
    	return $this->belongsToMany(User::class);
    }
```

We could also add some methods to delete a pivot entry, restore a pivot entry and force delete a pivot entry: 

```php
    public function softDeleteUser(User $user)
    {
    	return $this->users()->updateExistingPivot($user, ['deleted_at' => now()]);
    }

    public function restoreUser(User $user)
    {
    	return $this->users()->updateExistingPivot($user, ['deleted_at' => null]);
    }

    public function forceDeleteUser(User $user)
    {
    	return $this->users()->detach($user);
    }
```

**Comment by palomamtnez** [comment]
> @palomamtnez I'm interested in how you set your pivot table with soft delete and no model. What does your migration for that table look like? How do you soft delete a row?

Hey, thanks for your interest.
My Migration looks like this:

 ```
public function up()
    {// Create table for associating projects to users (Many-to-Many)
        Schema::create('user_project', function (Blueprint $table) {
            $table->integer('user_id')->unsigned();
            $table->integer('project_id')->unsigned();
            $table->softDeletes();
            $table->timestamps();

            $table->foreign('user_id')->references('id')->on('users')
                ->onUpdate('cascade')->onDelete('cascade');

            $table->foreign('project_id')->references('id')->on('project')
                ->onUpdate('cascade')->onDelete('cascade');
        });
    }
```


When I delete a user, I have this method in my User model:
 
```
protected static function boot()
    {
        parent::boot();

        static::deleting(function ($user) {     
            \DB::table('user_project')
                ->where('user_id', $user->id)
                ->update(array('deleted_at' => Carbon::now()));
        });

        static::restoring(function ($user) {
            $projectsId = Project::pluck('id')->toarray();
            \DB::table('user_project')
                ->where('user_id', $user->id)
                ->whereIn('project_id', $projectsId)
                ->update(array('deleted_at' => null));
        });
    }
```

And when a Project is deleted, I have this method in my Project class:

 protected static function boot() {
        parent::boot();

        static::deleting(function($project) {
            \DB::table('user_project')
                ->where('project_id', $project->id)
                ->update(array('deleted_at' => Carbon::now()));
        });

        static::restoring(function ($project) {
            $usersId = User::pluck('id')->toarray();
            \DB::table('user_project')
                ->where('project_id', $project->id)
                ->whereIn('user_id', $usersId)
                ->update(array('deleted_at' => null));
        });
    }

Note: when restoring a project, for example, I get the IDs of the Users that `are not deleted` (deleted_at column with a null value) by taking them with `$usersId = User::pluck('id')->toarray();`
Same when restoring a user.


Hope it helps!

**Comment by josecanhelp** [comment]
@palomamtnez we now support the deletion of pivot tables by using the configuration file in quicksand. We can thank @Jhnbrn90 for his work on this.

You may want to change the `models` key in your configuration to `deletables` and include the pivot table names as strings in your config. Check out the updated Readme for examples.

Cheers!
