### ISSUE TITLE
Verify that models included in Quicksand config have soft deletes enabled

### ISSUE THREAD

**Issue by besologic** [tightenco/quicksand#3]
http://stackoverflow.com/questions/25140768/how-to-determine-if-a-model-uses-soft-deletes-in-laravel-4-2

The second answer seems more reliable in situations where we have a model class that is extending a model class that has the trait on it, but I don't love the idea of being so tied into Laravel's implementation. 

@mattstauffer Do you have thoughts on how best to handle this?

**Comment by mattstauffer** [comment]
Does `class_uses` not work if you're extending a base class? If it works, I'd prefer that. If not, then yah I guess we need to test for that method :/
