### ISSUE TITLE
Foreign Key Constraints

### ISSUE THREAD

**Issue by pmatseykanets** [tightenco/quicksand#9]
First of all good job!

Now what about foreign key constraints? 

Please correct me if I'm wrong but it seems like the current implementation doesn't take these (FK) into consideration. This means that in some cases (when ON DELETE is set to RESTRICT) it simply won't work, but more importantly in other cases (when ON DELETE is set to CASCADE | SET NULL) it may potentially lead to data loss.

What I'm trying to say is it's probably worth mentioning in docs (readme).

Hope it makes sense. 
Thanks.

**Comment by mattstauffer** [comment]
@pmatseykanets I think Quicksand assumes that you're already handling that on your own, but I would love to see a PR to the docs to mention what you think people should understand if you have time/interest. Thanks! (sorry for the late response!)
